### ISSUE TITLE
Логика в presentation

### ISSUE THREAD

**Issue by mukovozov** [DmitriyTSt/HaHTestApp#18]
https://github.com/DmitriyTSt/HaHTestApp/blob/565c2089bf7cbd7f24cba6937b45751c01ba308c/app/src/main/java/ru/dmitriyt/hahtestapp/ui/login/LoginActivity.kt#L98

Вынести в locationRepository

**Comment by DmitriyTSt** [comment]
че делать с this? активити в качестве параметра?

**Comment by mukovozov** [comment]
Контекст передать
