### ISSUE TITLE
Что за класс?

### ISSUE THREAD

**Issue by mukovozov** [DmitriyTSt/HaHTestApp#24]
https://github.com/DmitriyTSt/HaHTestApp/blob/565c2089bf7cbd7f24cba6937b45751c01ba308c/app/src/main/java/ru/dmitriyt/hahtestapp/ui/login/LoginActivity.kt#L175

Посмотри permissionDispatcher

**Comment by DmitriyTSt** [comment]
Пользуюсь этим классом почти год, новое скорее всего потом изучу, нет смысла в тестовый проект тестовую для меня фичу пихать, но с этим ознакомился, прикольно выглядит

**Comment by mukovozov** [comment]
ну ок
