### ISSUE TITLE
Скоупы

### ISSUE THREAD

**Issue by mukovozov** [DmitriyTSt/HaHTestApp#5]
https://github.com/DmitriyTSt/HaHTestApp/blob/565c2089bf7cbd7f24cba6937b45751c01ba308c/app/src/main/java/ru/dmitriyt/hahtestapp/di/NetworkModule.kt#L22

Во всем модуле нет никаких скоупов. При каждом обращении будет создаваться новый объект. А каждая из операций ниже очень тяжелая.

**Comment by DmitriyTSt** [comment]
Заменил на singleton
