### ISSUE TITLE
Еще модуль для всего

### ISSUE THREAD

**Issue by mukovozov** [DmitriyTSt/HaHTestApp#7]
https://github.com/DmitriyTSt/HaHTestApp/blob/565c2089bf7cbd7f24cba6937b45751c01ba308c/app/src/main/java/ru/dmitriyt/hahtestapp/di/RepositoryModule.kt#L10

Советую тебе бить на модули и компоненты на фичи. 
Если будешь использовать скоупы, то будет много лишних объектов создано, что неправильно. И не по SOLIDу

**Comment by DmitriyTSt** [comment]
Не могу заинжектить через конструктор, так как хочу провайдить интерфейс а не реализацию
